### ISSUE TITLE
Ctrl+S seems to not work

### ISSUE THREAD

**Issue by justinmchase** [ryanmolden/ToolWindowHostedEditorExample#1]
I have been trying to use your sample here and it mostly works. I can get it to load up the editor and it even pulls in the syntax highlighting and all of that. But if I change the code and hit Ctrl+S it does not seem to actually write to disk.

I'm looking in the PreProcessMessage method of MyToolWindow and the //HACK: makes me very suspicious... but I really don't know what could be going wrong. Can you help at all?

**Comment by ryanmolden** [comment]
I can't repro this, save is working just fine for me on a simple C# file.  What language are you using?  What project type?  The HACK is just because there is a bug in the shell's TranslateAcceleratorEx where it will report that it didn't map the command and route it when in fact it did.  This is a bug in the VS shell, I fixed it soon after writing this example (I work on the VS shell team), but said fix hasn't been shipped so the 'HACK' is necessary in this case.

If the Exec is being hit when you hit Ctrl+S what is the call to EditorCommandTarget.Exec returning?  I assume 0 (S_OK), at least it is for me.  Is this file under source control?  Marked read-only on disk?  Does opening/saving in a normal editor work?

**Comment by justinmchase** [comment]
Ah, the language is actually a custom language of my own invention. Also, to make matters worse the file isn't part of the project. I wonder if that has something to do with it?

If you really wanted to try out the whole repro the source is in my project on codeplex: http://metasharp.codeplex.com

Here's the idea though. Basically my project is for ".g" files, which stands for grammar. I have a package and some exported taggers and such for syntax hilighting. I have also used your toolwindow sample to create a "Grammar Console" window. That grammar console tracks what grammar window you have active and it provides a .mdsl file which is put under user/appdata/ and opens the ITextBuffer for the toolwindow for the user to create sample input. I dynamically compile the grammars in the project then pass the input from the tool window into the generated grammar object and show the output. It's essentially a "language workbench" for creating DSLs. I actually undid the hack area and substituted it for something simpler that I found on a different sample, the simpler approach will save the buffer if closed but still only in memory. It never flushes to disk. It's very perplexing.

The return value I get in Exec is 0x80040100, which turns out to be OLECMDERR_E_NOTSUPPORTED. Not sure why...

**Comment by justinmchase** [comment]
PS the vs extension code is still in progress, so don't be too shocked to see weird stuff in there.

**Comment by ryanmolden** [comment]
<i><b>I actually undid the hack area and substituted it for something simpler that I found on a different sample</b></i>

Does that actually work in your editor?  I was curious as to where the call ended up and if the editor was just doing what I was doing (since they certainly don't have the complex logic the shell has around figuring out keybindings), so I substituted my code with the body of your PreProcessMessage and found that the editor method for PreProcessMessage always returns E_FAIL. So it basically does no keyboard processing. 

That is fine for the 'normal' editor (not hosted in a toolwindow) as the shell will understand that the editor's keybinding scope is active because the focus is in a document window.  

In our case the focus is in a toolwindow and I didn't set up any of the frame properties necessary to alert the shell that it should consider things from the editor keybinding scope.  The end result of replacing my code with yours is that lots of stuff stops working, specifically arrow navigation, tab, backspace, format selection, basically all editor commands.

 Typing still works, but most likely as an accident of the fact that the WM_CHAR is simply sent along its way to WPF and arrives at the editor as a KeyDown event.

You could make this work without the code I have by simply setting the VSFPROPID_InheritKeyBindings to the editor's GUID indicating to the shell that you would like the editor keybindings to be active inside your window.  If you do that you wouldn't need the PreProcessMessage override at all, I mentioned in my comments the reason I didn't do that was to show that you could have those bindings only be active when focus was in the editor and have no bindings / different bindings active if focus was in another part of your window, though granted my hosting window isn't very interesting and doesn't have any other focusable elements that would show off that kind of complexity.

<i><b>Also, to make matters worse the file isn't part of the project. I wonder if that has something to do with it?</b></i>

It may, I would have to dig into the save code but the shell is the one handling the command and it may be upset if the item to be saved has no owning hierarchy (project).  You could always test it by adding it to say the Miscellaneous Files project before opening the editor and see if save started working then. 

Perhaps you could bypass the shell here but the whole save process is rather complex in general, in your special case it may be enough to say cast the doc data to IVsPersistDocData and call Save on it if you don't have to worry about things like source control, multi-selection saves, integration with disaster recovery, files being read-only on disk, an initial Save being mapped to SaveAs if the file is a temporary file, etc...

<i><b>The return value I get in Exec is 0x80040100, which turns out to be OLECMDERR_E_NOTSUPPORTED. Not sure why...</b></i>

Yeah, I forgot the editor itself doesn't handle the save command, the shell does, mainly because it has the more complex logic around things like dealing with source control, handling a save when multiple items are selected, etc...

**Comment by ryanmolden** [comment]
Oh, I see, you set your InheritKeyBindings, in which case you don't need the PreProcessMessage override at all.  As the normal pre-translate the shell does will properly apply any editor keybindings and map them to commands and dispatch said command (at which point you forward it to the editor and life should be good).

**Comment by justinmchase** [comment]
I'll have to parse this response and try a few things and get back to you! Thanks though!

**Comment by justinmchase** [comment]
So I added this to Exec:
if (res == (int)Microsoft.VisualStudio.OLE.Interop.Constants.OLECMDERR_E_NOTSUPPORTED &&
    pguidCmdGroup.ToString() == "5efc7975-14bc-11cf-9b2b-00aa00573819" &&
    nCmdID == 331)
{
    Save(this.displayedFilePath);
}

Where Save just gets the docdata like in GetBufferAt but instead casts it to IVsPersistDocData like you suggested and it works!

The only thing left regarding that is how to detect a Ctrl+Shift+S (Save All)? It's not sending input to my window, which makes sense, and I tried attaching to dte.Events.CommandEvents.AfterExecute but it does not seem to be fired for SaveAll. Any suggestions? Also is there a constant for the Guid above somewhere?

**Comment by justinmchase** [comment]
Ok turns out I was able to implement IVsRunningDocTableEvents and register myself with the IVsRunningDocumentTable service which calls me during a SaveAll! So I suppose that solves the last of it. I'm content for now, thanks for the demo and the help!

**Comment by ryanmolden** [comment]
Yes, the shell uses the running document table to handle all saves.  As for if there is a constant to recognize save commands you probably want something like this

```
 private static bool IsSaveCommand(ref Guid commandGuid, uint commandId)
 {
     return ((commandGuid == VSConstants.GUID_VSStandardCommandSet97) &&
                 ((commandId == (uint)VSConstants.VSStd97CmdID.SaveProjectItem /*This is Save*/) || 
                  (commandId == (uint)VSConstants.VSStd97CmdID.SaveSolution /*This is SaveAll*/));
}
```

As for your AfterExecute not being fired, you are probably falling victim to the CLR making a COM IConnectionPointContainer 'look like' an event at the interop layer.  The one known problem with it doing this is the event object it returns when you += a handler is a temporary object and has no root, so if you don't save a strong ref to it it will be GCed out from underneath you.  I noticed you signed up for a couple of other events around window activation that likely suffer from the same fate.  They may appear to work for awhile, but eventually they will be GCed and you will stop receiving events.

**Comment by justinmchase** [comment]
I read about that issue somewhere else, so I took out a reference to the specific Events object just to prevent the GC from collecting them. I tried that with the CommandEvents also but it either didn't work or there was some other problem. Thanks again.

**Comment by justinmchase** [comment]
Right, specifically I had this code:

this.dte = dte;
this.solutionEvents = dte.Events.SolutionEvents;
this.projectItemsEvents = dte.Events.MiscFilesEvents;

Also in the toolwindow I am taking a reference on the WindowEvents object.
Didn't seem to work for the DocumentEvents though, very strange.

On Sun, Sep 11, 2011 at 10:45 PM, Ryan Molden <
reply@reply.github.com>wrote:

> It's not the Events object, that is a COM object, it is the object that
> directly 'owns' the.NET event that you sign up to, that doesn't really exist
> (COM objects can't have .NET events on them), the CLR conjures it up when
> you request it to sign-up, but it has nowhere to store it since it can't
> 'stash it' away on the COM object it allegedly came from.  You would need to
> keep a reference to the CommandEvents object.  It doesn't matter for you
> anymore if you don't need those events, but it is a commonly encountered
> problem due to the interop layer exposing connection points as individual
> .NET events.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ryanmolden/ToolWindowHostedEditorExample/issues/1#issuecomment-2067488

## 

Justin Chase
http://www.justinmchase.com
